"""
API Schemas 模块

导出所有 Pydantic 模型。
"""

from app.api.schemas.ai import (
    AIChatRequest,
    AIChatResponse,
    AIMessageListResponse,
    AIMessageResponse,
    AISessionCreate,
    AISessionListResponse,
    AISessionResponse,
    VectorSearchRequest,
    VectorSearchResponse,
    VectorSearchResult,
)
from app.api.schemas.auth import (
    AuthResponse,
    CodeSentResponse,
    EmailCodeRequest,
    EmailVerifyRequest,
    OAuthProviderInfo,
    SessionResponse,
    TokenRefreshRequest,
    TokenResponse,
    UserResponse,
)
from app.api.schemas.book import (
    BookContentResponse,
    BookCoverResponse,
    BookDeleteResponse,
    BookListResponse,
    BookMetaResponse,
    BookResponse,
    BookUpdateRequest,
    DedupReferenceRequest,
    UploadCompleteRequest,
    UploadInitRequest,
    UploadInitResponse,
)
from app.api.schemas.note import (
    BookmarkCreate,
    BookmarkListResponse,
    BookmarkResponse,
    DeleteResponse,
    HighlightCreate,
    HighlightListResponse,
    HighlightResponse,
    HighlightUpdate,
    NoteCreate,
    NoteListResponse,
    NoteResponse,
    NoteUpdate,
    ShelfBookAdd,
    ShelfBookRemove,
    ShelfCreate,
    ShelfListResponse,
    ShelfResponse,
    ShelfUpdate,
)

__all__ = [
    # AI
    "AIChatRequest",
    "AIChatResponse",
    "AIMessageListResponse",
    "AIMessageResponse",
    "AISessionCreate",
    "AISessionListResponse",
    "AISessionResponse",
    "VectorSearchRequest",
    "VectorSearchResponse",
    "VectorSearchResult",
    # Auth
    "AuthResponse",
    "CodeSentResponse",
    "EmailCodeRequest",
    "EmailVerifyRequest",
    "OAuthProviderInfo",
    "SessionResponse",
    "TokenRefreshRequest",
    "TokenResponse",
    "UserResponse",
    # Book
    "BookContentResponse",
    "BookCoverResponse",
    "BookDeleteResponse",
    "BookListResponse",
    "BookMetaResponse",
    "BookResponse",
    "BookUpdateRequest",
    "DedupReferenceRequest",
    "UploadCompleteRequest",
    "UploadInitRequest",
    "UploadInitResponse",
    # Note
    "BookmarkCreate",
    "BookmarkListResponse",
    "BookmarkResponse",
    "DeleteResponse",
    "HighlightCreate",
    "HighlightListResponse",
    "HighlightResponse",
    "HighlightUpdate",
    "NoteCreate",
    "NoteListResponse",
    "NoteResponse",
    "NoteUpdate",
    "ShelfBookAdd",
    "ShelfBookRemove",
    "ShelfCreate",
    "ShelfListResponse",
    "ShelfResponse",
    "ShelfUpdate",
]
