"""
API Schemas 模块

导出所有 Pydantic 模型。
"""

from app.api.schemas.ai import (
    AIChatRequest,
    AIChatResponse,
    AIMessageListResponse,
    AIMessageResponse,
    AISessionCreate,
    AISessionListResponse,
    AISessionResponse,
    VectorSearchRequest,
    VectorSearchResponse,
    VectorSearchResult,
)
from app.api.schemas.auth import (
    AuthResponse,
    CodeSentResponse,
    EmailCodeRequest,
    EmailVerifyRequest,
    OAuthProviderInfo,
    SessionResponse,
    TokenRefreshRequest,
    TokenResponse,
    UserResponse,
)
from app.api.schemas.billing import (
    AppleIAPVerifyRequest,
    CheckoutRequest,
    CheckoutResponse,
    CreditBalanceResponse,
    CreditProductListResponse,
    CreditProductResponse,
    GoogleIAPVerifyRequest,
    IAPVerifyResponse,
    PaymentHistoryItem,
    PaymentHistoryResponse,
    PlanListResponse,
    PlanResponse,
    SubscriptionResponse,
)
from app.api.schemas.book import (
    BookContentResponse,
    BookCoverResponse,
    BookDeleteResponse,
    BookListResponse,
    BookMetaResponse,
    BookResponse,
    BookUpdateRequest,
    DedupReferenceRequest,
    UploadCompleteRequest,
    UploadInitRequest,
    UploadInitResponse,
)
from app.api.schemas.export import (
    ExportBook,
    ExportHighlight,
    ExportNote,
    ExportSummary,
    NotesExportResponse,
)
from app.api.schemas.invite import (
    InviteCodeResponse,
    InviteeItem,
    InviteeListResponse,
    InviteRewardRule,
    InviteRulesResponse,
    InviteStatsResponse,
)
from app.api.schemas.note import (
    BookmarkCreate,
    BookmarkListResponse,
    BookmarkResponse,
    DeleteResponse,
    HighlightCreate,
    HighlightListResponse,
    HighlightResponse,
    HighlightUpdate,
    NoteCreate,
    NoteListResponse,
    NoteResponse,
    NoteUpdate,
    ShelfBookAdd,
    ShelfBookRemove,
    ShelfCreate,
    ShelfListResponse,
    ShelfResponse,
    ShelfUpdate,
)
from app.api.schemas.reading import (
    BookPositionResponse,
    BookPositionUpdate,
    BookReadingProgress,
    DailyReadingStats,
    MonthlyReadingStats,
    ReadingHistoryItem,
    ReadingHistoryResponse,
    ReadingStatsResponse,
    ReadingTimeLogCreate,
    ReadingTimeLogResponse,
    ReadingTimeLogUpdate,
    RecentBooksResponse,
    WeeklyReadingStats,
)
from app.api.schemas.user import (
    AccountDeleteRequest,
    AccountDeleteResponse,
    NotificationSettingsResponse,
    NotificationSettingsUpdate,
)

__all__ = [
    # AI
    "AIChatRequest",
    "AIChatResponse",
    "AIMessageListResponse",
    "AIMessageResponse",
    "AISessionCreate",
    "AISessionListResponse",
    "AISessionResponse",
    "VectorSearchRequest",
    "VectorSearchResponse",
    "VectorSearchResult",
    # Auth
    "AuthResponse",
    "CodeSentResponse",
    "EmailCodeRequest",
    "EmailVerifyRequest",
    "OAuthProviderInfo",
    "SessionResponse",
    "TokenRefreshRequest",
    "TokenResponse",
    "UserResponse",
    # Book
    "BookContentResponse",
    "BookCoverResponse",
    "BookDeleteResponse",
    "BookListResponse",
    "BookMetaResponse",
    "BookResponse",
    "BookUpdateRequest",
    "DedupReferenceRequest",
    "UploadCompleteRequest",
    "UploadInitRequest",
    "UploadInitResponse",
    # Note
    "BookmarkCreate",
    "BookmarkListResponse",
    "BookmarkResponse",
    "DeleteResponse",
    "HighlightCreate",
    "HighlightListResponse",
    "HighlightResponse",
    "HighlightUpdate",
    "NoteCreate",
    "NoteListResponse",
    "NoteResponse",
    "NoteUpdate",
    "ShelfBookAdd",
    "ShelfBookRemove",
    "ShelfCreate",
    "ShelfListResponse",
    "ShelfResponse",
    "ShelfUpdate",
    # Reading
    "BookPositionResponse",
    "BookPositionUpdate",
    "BookReadingProgress",
    "DailyReadingStats",
    "MonthlyReadingStats",
    "ReadingHistoryItem",
    "ReadingHistoryResponse",
    "ReadingStatsResponse",
    "ReadingTimeLogCreate",
    "ReadingTimeLogResponse",
    "ReadingTimeLogUpdate",
    "RecentBooksResponse",
    "WeeklyReadingStats",
    # Billing
    "AppleIAPVerifyRequest",
    "CheckoutRequest",
    "CheckoutResponse",
    "CreditBalanceResponse",
    "CreditProductListResponse",
    "CreditProductResponse",
    "GoogleIAPVerifyRequest",
    "IAPVerifyResponse",
    "PaymentHistoryItem",
    "PaymentHistoryResponse",
    "PlanListResponse",
    "PlanResponse",
    "SubscriptionResponse",
    # Invite
    "InviteCodeResponse",
    "InviteeItem",
    "InviteeListResponse",
    "InviteRewardRule",
    "InviteRulesResponse",
    "InviteStatsResponse",
    # Export
    "ExportBook",
    "ExportHighlight",
    "ExportNote",
    "ExportSummary",
    "NotesExportResponse",
    # User
    "AccountDeleteRequest",
    "AccountDeleteResponse",
    "NotificationSettingsResponse",
    "NotificationSettingsUpdate",
]
